
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
      - ./etc/config.d:/etc/clickhouse-server/config.d
      - ./etc/users.d:/etc/clickhouse-server/users.d
      - ./etc/dicts:/etc/clickhouse-server/dicts
      #- ./etc/etc:/etc/clickhouse-server
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
